wp_pj8/habit/habit/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include ######################

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hb_main.urls', namespace='hb_main')), ########################
]

wp_pj8/habit/hb_main/urls.py
from django.conf.urls import url
from django.urls import path
from . import views #view와 연결하기 위해서

app_name="hb_main" #namespace

urlpatterns =[
    path('', views.home, name='home'),
    url(r'^result/', views.result, name='result'),
    url(r'^adding/$', views.adding, name='adding'),
    url(r'^doit/$', views.doit, name='doit'),
    url(r'^statistics/(?P<habit_id>\d+)/$', views.statistics, name='statistics'),
    url(r'^deleting/$', views.deleting, name='deleting'),
    url(r'^statistics2/(?P<habit_id>\d+)/$', views.statistics2, name='statistics2'),
    url(r'^updating/$', views.updating, name='updating'),
    url(r'^updating/(?P<habit_id>\d+)/$', views.updating, name='updating'),
]

wp_pj8/habit/hb_main/models.py
from django.db import models
import datetime


class Habit(models.Model):
    name = models.CharField(max_length=100)
    start_day=models.DateTimeField(auto_now_add=False, default=datetime.datetime.today())
    do_it=models.BooleanField(null=True)
    do_it_list=models.TextField(null=True)
    end=models.BooleanField(null=False, default=False)

    def __str__(self):
        return self.name

class end_Habit(models.Model):
    name = models.CharField(max_length=100)
    start_day=models.DateTimeField(auto_now_add=False, default=datetime.datetime.today())
    do_it_list=models.TextField(null=True)

    def __str__(self):
        return self.name

wp_pj8/habit/hb_main/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse #################
from .models import Habit, end_Habit ################
import json
import datetime
import openpyxl
from . import dateRange
import pandas
import matplotlib.pyplot
from calendar import HTMLCalendar
from . import HTMLCalendar
import calendar
from . import statistic_html
import pytz
import sys
import os

def home(request): #함수로 구현
    return render(request, 'hb_main/home.html')

def result(request): 
    name = request.POST.get('name')  #######################################
    utc=pytz.UTC
    habits = Habit.objects.all()
    KST = pytz.timezone('Asia/Seoul')
    for i in habits:
        end=i.start_day+datetime.timedelta(days=65)
        #utc.localize(end)
        td=datetime.datetime.now()
        utc.localize(td)
        #datetime.datetime.today()=utc.localize(datetime.datetime.today())
        if end<=utc.localize(td): #습관의 마지막 날짜보다 오늘 날짜가 크면,
            i.end=True #객체의 end값을 True로 변경
            i.save()
        if i.end==True: #end가 True가 된 객체들을,
            end_habit=end_Habit.objects.create(name=i.name,start_day=i.start_day,do_it_list=i.do_it_list)
            end_habit.save() #end_Habit 모델로 추가(66일이 지나서 끝난 습관 모델)
            i.delete() #Habit 모델에서는 삭제(습관 모델)
    end_habits=end_Habit.objects.all()
    context={'habits':habits, 'end_habits':end_habits} 
    return render(request, 'hb_main/result.html', context)
    #habit = Habit.objects.all()
    #return HttpResponse("asdf")

def adding(request): 
    if request.method == 'POST':
        #return HttpResponse(request)
        habit=Habit.objects.create(name=request.POST['name'])
        dates=list()
        habit.do_it_list=json.dumps(dates) #객체의 do_it_list 필드에는 리스트 형태로 날짜 저장
        habit.save()
        return render(request, 'hb_main/home.html')
    return render(request, 'hb_main/adding.html')
    
def doit(request): #*
    if request.method == 'POST':
        select = request.POST['true']
        Doit=Habit.objects.get(id=select)
        Doit.do_it=True
        jsonDec=json.decoder.JSONDecoder()
        dates=jsonDec.decode(Doit.do_it_list)
        dates.append((datetime.datetime.today()).strftime("%Y-%m-%d"))
        Doit.do_it_list=json.dumps(dates)
        Doit.save()
        return render(request,'hb_main/doit.html')

def statistics(request, habit_id): #*
    if request.method == 'GET':
        select = request.GET.get('habit_id')
        statistic=Habit.objects.get(id=habit_id)
        context={'statistic':statistic}
        jsonDec=json.decoder.JSONDecoder() #데이터베이스에 있는 실천 여부 정보 리스트로 받아오기
        dates=jsonDec.decode(statistic.do_it_list)
        wb=openpyxl.Workbook() #엑셀에 정보 추가
        file='./day.xlsx'
        wb.active.title="habit_day_66"
        w1=wb["habit_day_66"]
        end_day=statistic.start_day + datetime.timedelta(days=65)
        days=dateRange.date_list(statistic.start_day,end_day)
        w1.cell(1,1).value="date"
        w1.cell(1,2).value="action"
        for i in range(2,len(days)+2):
            w1.cell(i,1).value=days[i-2] #날짜 추가
        get_cells = w1['A2':'A67']
        num=1
        for i in get_cells:
            for j in i:
                num+=1
                for n in dates:
                    if j.value==n:
                        w1.cell(num,2).value="True" #실천 여부 추가
        wb.save(file)
        html_file=statistic_html.make_html()
        dir = os.path.dirname(os.path.realpath('day.xlsx'))
        temp = dir + '\\day.xlsx'
        data=pandas.read_excel(temp) #엑셀 데이터 읽기
        # data=pandas.read_excel("C:\\Users\\subin\\Desktop\\habitt\\6ha6it\\wp_pj8\\habit\\day.xlsx") #엑셀 데이터 읽기
        data=pandas.DataFrame(data)
        htmlCalendar = HTMLCalendar.HTMLCalendar(calendar.SUNDAY)
        month_action=list() #엑셀에 있는 날짜 문자열에서 월 정수형 정보 중복없이 가져오기
        for m in data.date:
            month_action.append(int(m[5:7]))
        month_set=set(month_action)
        month_action=list(month_set)
        html_file=statistic_html.month_html(htmlCalendar, sorted(month_action), data)
        html_file=statistic_html.day_html(data)
        html_file=statistic_html.week_html(data)
        return render(request, 'hb_main/statistics.html', context)

def deleting(request):
    if request.method == "POST":
        if request.POST.get('del_habit')!=None:
            habit=request.POST.get('del_habit')
            del_habit=end_Habit.objects.get(name=habit)
            del_habit.delete()
            return render(request, 'hb_main/deleting.html')
        else:
            habit=request.POST.get('del_habit2')
            del_habit=Habit.objects.get(name=habit)
            del_habit.delete()
            return render(request, 'hb_main/deleting.html')

def statistics2(request, habit_id):
    if request.method == 'GET':
        select = request.GET.get('habit_id')
        statistic=end_Habit.objects.get(id=habit_id)
        context={'statistic':statistic}
        jsonDec=json.decoder.JSONDecoder() #데이터베이스에 있는 실천 여부 정보 리스트로 받아오기
        dates=jsonDec.decode(statistic.do_it_list)
        wb=openpyxl.Workbook() #엑셀에 정보 추가
        file='./day.xlsx'
        wb.active.title="habit_day_66"
        w1=wb["habit_day_66"]
        end_day=statistic.start_day + datetime.timedelta(days=65)
        days=dateRange.date_list(statistic.start_day,end_day)
        w1.cell(1,1).value="date"
        w1.cell(1,2).value="action"
        for i in range(2,len(days)+2):
            w1.cell(i,1).value=days[i-2] #날짜 추가
        get_cells = w1['A2':'A67']
        num=1
        for i in get_cells:
            for j in i:
                num+=1
                for n in dates:
                    if j.value==n:
                        w1.cell(num,2).value="True" #실천 여부 추가
        wb.save(file)
        html_file=statistic_html.make_html()
        dir = os.path.dirname(os.path.realpath('day.xlsx'))
        temp = dir + '\\day.xlsx'
        data=pandas.read_excel(temp) #엑셀 데이터 읽기
        # data=pandas.read_excel("\\6ha6it\\wp_pj8\\habit\\day.xlsx") #엑셀 데이터 읽기
        data=pandas.DataFrame(data)
        htmlCalendar = HTMLCalendar.HTMLCalendar(calendar.SUNDAY)
        month_action=list() #엑셀에 있는 날짜 문자열에서 월 정수형 정보 중복없이 가져오기
        for m in data.date:
            month_action.append(int(m[5:7]))
        month_set=set(month_action)
        month_action=list(month_set)
        html_file=statistic_html.month_html(htmlCalendar, sorted(month_action), data)
        html_file=statistic_html.day_html(data)
        html_file=statistic_html.week_html(data)
        return render(request, 'hb_main/statistics.html', context)


def updating(request, habit_id=None):
    global up_habit
    if request.method == "GET":
        #temp=request.POST.get(habit_id)
        up_habit=Habit.objects.get(id=habit_id)
        up_habit=habit_id
        #up=Habit.objects.get(name=temp)
        #return HttpResponse(up_habit)
    if request.method == "POST":
        habit=request.POST.get('up_habit')
        up=Habit.objects.get(id=up_habit)
        habit=Habit.objects.filter(id=up_habit)
        #return HttpResponse(up.name)
        if request.POST.get('name')!="":
            habit.update(name=request.POST.get('name'))
        if request.POST.get('start_day')!="":
            habit.update(start_day=request.POST.get('start_day'))
            
        if request.POST.get('action_day')!="":
            do=request.POST.get('action_day')
            #return HttpResponse(up.do_it_list)
            jsonDec=json.decoder.JSONDecoder()
            dates=jsonDec.decode(up.do_it_list)
            dates.append(do)
            habit.update(do_it_list=json.dumps(dates))
            #return HttpResponse(type(dates))
        if request.POST.get('no_action_day')!="":
            no_do=request.POST.get('no_action_day')
            jsonDec=json.decoder.JSONDecoder()
            dates=jsonDec.decode(up.do_it_list)
            dates.remove(no_do)
            habit.update(do_it_list=json.dumps(dates))
        return render(request, 'hb_main/home.html')
    return render(request, 'hb_main/updating.html')

wp_pj8/habit/hb_main/templates/hb_main/adding.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>추가 페이지입니다.</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'hb_main/adding.css' %}">
</head>
<body>
    <div style="text-align: center;">
    <form action={% url 'hb_main:adding' %} method="POST">
        {% csrf_token %}
        <input placeholder="습관을 입력하세요" name="name" style="height: 20px; width: 300px;"/>
        <button type="submit" id="habit-add">습관 추가 →</button>
    </form>
    </div>
</body>
</html>

wp_pj8/habit/hb_main/templates/hb_main/deleting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>삭제</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'hb_main/deleting.css' %}">
</head>
<body>
    <div style="text-align: center;">
    <h1>삭제되었습니다</h1>
    <a href="{% url 'hb_main:result' %}" id="go_habit">back</a>
</div>
</body>
</html>

wp_pj8/habit/hb_main/templates/hb_main/doit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>홈</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'hb_main/doit.css' %}">
</head>
<body>
    <div class="container" style="text-align: center;">
    <h1>축하해요!</h1>
    <a href="{% url 'hb_main:result' %}">back</a>
    </div>
</body>
</html>

wp_pj8/habit/hb_main/templates/hb_main/home.html
<!DOCTYPE html>

<html lang="en">
<head>
    <title>홈</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'hb_main/home.css' %}">
</head>
<body>
    <div class="container">
    <p id="intro">66일 습관 형성 프로젝트<br><br></p>
    <p>6ha6it'</p>
    <p id="famous">"새로운 행동에 대한 거부감이 사라지는 데는<br> 평균 21일이 습관으로 만들어지는 데는 66일이 걸린다"<br><br></p>
    <p id="dr">- 필리파 렐리 박사 </p>    
    </div>
    <a href="{% url 'hb_main:result' %}"><button id="go_habit">습관 만들기 →</button></a>
</body>
</html>

wp_pj8/habit/hb_main/templates/hb_main/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>습관</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'hb_main/result.css' %}">
</head>
<body>
    <div class="container" style="width:35%;float:left;margin-left: 10%;">
        <p id="app-name">6ha6it'</p>
        <p class="text-text">진행 중인 습관</p>
        <table class="table1">
            <thead>
            <tr>
                <td><B>이름</B></td>
                <td><B>실천</B></td>
                <td><B>삭제</B></td>
                <td><B>수정</B></td>
            </tr>
            </thead>
            <tbody>
            {% for habit in habits %}
            <tr>
                <td>
                    <form action="/statistics/{{habit.id}}/" method="GET">
                        {% csrf_token %}
                        <a href="/statistics/{{habit.id}}/" name="statistics" value="{{habit.id}}">{{habit.name}}</a>
                    </form>
                </td>
                <td>
                    <form action="{% url 'hb_main:doit' %}" method="POST">
                        {% csrf_token %}
                        <button name="true" value="{{habit.id}}" class="btn">
                            <img src="{% static 'hb_main/image/yes.png' %}" style="width: 30px; height: 30px;">
                        </button>
                    </form>
                </td>
                <td>
                    <form action="{% url 'hb_main:deleting' %}" method="POST">
                        {% csrf_token %}
                        <button name="del_habit2" value="{{habit.name}}" class="btn">
                            <img src="{% static 'hb_main/image/del.png' %}" style="width: 30px; height: 30px;">
                        </button>
                    </form>
                </td>
                <td>
                    <form action="/updating/{{habit.id}}/" method="GET">
                        {% csrf_token %}
                        <button name="up_habit" value="{{habit.id}}" class="btn">
                            <img src="{% static 'hb_main/image/update.png' %}" style="width: 30px; height: 30px;">
                        </button>
                    </form>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'hb_main:adding' %}" id="add">+</a>
        </div>
        <div class="container" style="width:35%;float:right;margin-right: 10%;">
        <p class="text-text" id="text2">완료된 습관</p>
        <table class="table2">
            <thead>
                <tr>
                    <td><B>이름</B></td>
                    <td><B>삭제</B></td>
                </tr>
                </thead>
                <tbody>
                    {% for end_habit in end_habits %}
                    <tr>
                        <td>
                            <form action="/statistics2/{{end_habit.id}}/" method="GET">
                                {% csrf_token %}
                                <a href="/statistics2/{{end_habit.id}}/" name="statistics" value="{{end_habit.id}}" id="link2">{{end_habit.name}}</a>
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'hb_main:deleting' %}" method="POST">
                                {% csrf_token %}
                                <button name="del_habit" value="{{end_habit.name}}" class="btn">
                                    <img src="{% static 'hb_main/image/del.png' %}" style="width: 30px; height: 30px;">
                                </button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
        </table>
    </div>
</body>
</html>

wp_pj8/habit/hb_main/templates/hb_main/statistics.html
<html>
<head>
<title>statics</title>
{% load static %}
<style type="text/css">
#body {
background: white url("background.jpg") repeat;
}
.stat-body{background: url("../../static/hb_main/image/background.jpg")}
#calendar {

border-radius: 5px;
-moz-border-radius: 5px;
}
#calendar table {
border-collapse: collapse;
background-color: white;
margin: 10px auto;
font-size: 18px;
padding: 0px
border= 0px;
}
td, th {

text-align: center;
vertical-align: middle;
color: #444;
position: relative;
}
th {

font-weight: bold;
font-size: 14px;
border: 1px solid #444444;}
tbody{width: 40px;}th.month {
text-align: center;
}
td {
border: 1px solid #444444;
 width: 40px;}
td.noday {
border: 0px;
}
td:hover {
color: #222;
}
td.action_day {
color:#21b7d5;;
font-weight: bold;
}
</style>
</head>
<body class="stat-body">
<div id="calendar" style="display:flex; margin-left: 330px"><table class="month" style="margin-left: -100px; background:transparent;border: 1px solid #444444;border-collapse: collapse;width: 300px; height: 300px;">
<tr><th colspan="7" class="month">September 2021</th></tr>
<tr><th class="sun">Sun</th><th class="mon">Mon</th><th class="tue">Tue</th><th class="wed">Wed</th><th class="thu">Thu</th><th class="fri">Fri</th><th class="sat">Sat</th></tr>
<tr><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="action_day wed">1</td><td class="action_day thu">2</td><td class="action_day fri">3</td><td class="action_day sat">4</td></tr>
<tr><td class="sun">5</td><td class="mon">6</td><td class="action_day tue">7</td><td class="wed">8</td><td class="thu">9</td><td class="fri">10</td><td class="action_day sat">11</td></tr>
<tr><td class="action_day sun">12</td><td class="mon">13</td><td class="tue">14</td><td class="wed">15</td><td class="action_day thu">16</td><td class="fri">17</td><td class="sat">18</td></tr>
<tr><td class="action_day sun">19</td><td class="mon">20</td><td class="action_day tue">21</td><td class="action_day wed">22</td><td class="action_day thu">23</td><td class="action_day fri">24</td><td class="action_day sat">25</td></tr>
<tr><td class="action_day sun">26</td><td class="action_day mon">27</td><td class="action_day tue">28</td><td class="wed">29</td><td class="action_day thu">30</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td></tr>
</table>
<table class="month" style="margin-left: -100px; background:transparent;border: 1px solid #444444;border-collapse: collapse;width: 300px; height: 300px;">
<tr><th colspan="7" class="month">October 2021</th></tr>
<tr><th class="sun">Sun</th><th class="mon">Mon</th><th class="tue">Tue</th><th class="wed">Wed</th><th class="thu">Thu</th><th class="fri">Fri</th><th class="sat">Sat</th></tr>
<tr><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="action_day fri">1</td><td class="action_day sat">2</td></tr>
<tr><td class="sun">3</td><td class="mon">4</td><td class="action_day tue">5</td><td class="wed">6</td><td class="thu">7</td><td class="action_day fri">8</td><td class="sat">9</td></tr>
<tr><td class="sun">10</td><td class="action_day mon">11</td><td class="tue">12</td><td class="wed">13</td><td class="thu">14</td><td class="fri">15</td><td class="action_day sat">16</td></tr>
<tr><td class="action_day sun">17</td><td class="action_day mon">18</td><td class="action_day tue">19</td><td class="wed">20</td><td class="action_day thu">21</td><td class="fri">22</td><td class="sat">23</td></tr>
<tr><td class="sun">24</td><td class="mon">25</td><td class="action_day tue">26</td><td class="action_day wed">27</td><td class="action_day thu">28</td><td class="action_day fri">29</td><td class="action_day sat">30</td></tr>
<tr><td class="sun">31</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td></tr>
</table>
<table class="month" style="margin-left: -100px; background:transparent;border: 1px solid #444444;border-collapse: collapse;width: 300px; height: 300px;">
<tr><th colspan="7" class="month">November 2021</th></tr>
<tr><th class="sun">Sun</th><th class="mon">Mon</th><th class="tue">Tue</th><th class="wed">Wed</th><th class="thu">Thu</th><th class="fri">Fri</th><th class="sat">Sat</th></tr>
<tr><td class="noday">&nbsp;</td><td class="action_day mon">1</td><td class="action_day tue">2</td><td class="action_day wed">3</td><td class="thu">4</td><td class="fri">5</td><td class="sat">6</td></tr>
<tr><td class="sun">7</td><td class="mon">8</td><td class="tue">9</td><td class="wed">10</td><td class="thu">11</td><td class="fri">12</td><td class="sat">13</td></tr>
<tr><td class="sun">14</td><td class="mon">15</td><td class="tue">16</td><td class="wed">17</td><td class="thu">18</td><td class="fri">19</td><td class="sat">20</td></tr>
<tr><td class="sun">21</td><td class="mon">22</td><td class="tue">23</td><td class="wed">24</td><td class="thu">25</td><td class="fri">26</td><td class="sat">27</td></tr>
<tr><td class="sun">28</td><td class="mon">29</td><td class="tue">30</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td></tr>
</table>
</div>
<div class="img-container" style="margin-left: 330px;"><img src="{% static 'hb_main/image/savefig_day.png' %}" style="width: 500px; height: 400px;"><img src="{% static 'hb_main/image/savefig_week.png' %}" style="width: 500px; height: 400px;"></div>
</body>
</html>

wp_pj8/habit/hb_main/templates/hb_main/updating.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>수정 페이지입니다.</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'hb_main/updating.css' %}">
</head>
<body>
    <div style="text-align: center;">
    <form action={% url 'hb_main:updating' %} method="POST">
        {% csrf_token %}
        <input placeholder="습관을 입력하세요" name="name" style="height: 20px; width: 300px;"/>
        <input placeholder="시작일: ex)2021-05-27" name="start_day" style="height: 20px; width: 300px;"/>
        <input placeholder="실천일을 입력하세요" name="action_day" style="height: 20px; width: 300px;"/>
        <input placeholder="실천하지 않은 날을 입력하세요" name="no_action_day" style="height: 20px; width: 300px;"/>
        <button name="up_habit" type="submit" value="{{habit.name}}" id="update">습관 수정 →</button>
    </form>
    </div>
</body>
</html>